version: '3'
services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    volumes:
      - 'mongodb_data:/bitnami'
    networks: 
     - parse
  parse:
    image: 'bitnami/parse:3'
    environment:
     - MONGODB_HOST=mongodb
     - PARSE_HOST=206.189.41.127
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
    networks: 
     - parse
  parse-dashboard:
    image: 'bitnami/parse-dashboard:2.0.4'
    environment:
        - PARSE_DASHBOARD_PASSWORD=1234
        - PARSE_DASHBOARD_USER=test
        - PARSE_HOST=206.189.41.127
        - PARSE_PORT_NUMBER=1337
        - PARSE_USE_HOSTNAME=no
        - NAMI_DEBUG='--log-level=trace'
    ports:
      - '80:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
        #    networks: 
        #     - parse
volumes:
  mongodb_data:
  parse_data:
  parse_dashboard_data:
networks: 
    parse:
